/* soapServer.cpp
   Generated by gSOAP 2.8.101 for iMesImage.h

gSOAP XML Web services tools
Copyright (C) 2000-2020, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.8.101 2020-05-24 14:18:11 GMT")
extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	soap->keep_alive = soap->max_keep_alive + 1;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->keep_alive > 0 && soap->max_keep_alive > 0)
			soap->keep_alive--;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if ((soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap))) && soap->error && soap->error < SOAP_STOP)
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}
#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	(void)soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:uploadData"))
		return soap_serve_ns__uploadData(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:DownloadData"))
		return soap_serve_ns__DownloadData(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:test1"))
		return soap_serve_ns__test1(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__uploadData(struct soap *soap)
{	struct ns__uploadData soap_tmp_ns__uploadData;
	struct ns__uploadDataResponse soap_tmp_ns__uploadDataResponse;
	char * soap_tmp_string;
	soap_default_ns__uploadDataResponse(soap, &soap_tmp_ns__uploadDataResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns__uploadDataResponse.result = &soap_tmp_string;
	soap_default_ns__uploadData(soap, &soap_tmp_ns__uploadData);
	if (!soap_get_ns__uploadData(soap, &soap_tmp_ns__uploadData, "ns:uploadData", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__uploadData(soap, soap_tmp_ns__uploadData.macCode, soap_tmp_ns__uploadData.wipEntityId, soap_tmp_ns__uploadDataResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = ""; /* use SOAP encoding style */
	soap_serializeheader(soap);
	soap_serialize_ns__uploadDataResponse(soap, &soap_tmp_ns__uploadDataResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__uploadDataResponse(soap, &soap_tmp_ns__uploadDataResponse, "ns:uploadDataResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__uploadDataResponse(soap, &soap_tmp_ns__uploadDataResponse, "ns:uploadDataResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__DownloadData(struct soap *soap)
{	struct ns__DownloadData soap_tmp_ns__DownloadData;
	struct ns__DownloadDataResponse soap_tmp_ns__DownloadDataResponse;
	char * soap_tmp_string;
	soap_default_ns__DownloadDataResponse(soap, &soap_tmp_ns__DownloadDataResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns__DownloadDataResponse.value = &soap_tmp_string;
	soap_default_ns__DownloadData(soap, &soap_tmp_ns__DownloadData);
	if (!soap_get_ns__DownloadData(soap, &soap_tmp_ns__DownloadData, "ns:DownloadData", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__DownloadData(soap, soap_tmp_ns__DownloadData.data, soap_tmp_ns__DownloadDataResponse.value);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = ""; /* use SOAP encoding style */
	soap_serializeheader(soap);
	soap_serialize_ns__DownloadDataResponse(soap, &soap_tmp_ns__DownloadDataResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__DownloadDataResponse(soap, &soap_tmp_ns__DownloadDataResponse, "ns:DownloadDataResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__DownloadDataResponse(soap, &soap_tmp_ns__DownloadDataResponse, "ns:DownloadDataResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__test1(struct soap *soap)
{	struct ns__test1 soap_tmp_ns__test1;
	struct ns__test1Response soap_tmp_ns__test1Response;
	soap_default_ns__test1Response(soap, &soap_tmp_ns__test1Response);
	soap_default_ns__test1(soap, &soap_tmp_ns__test1);
	if (!soap_get_ns__test1(soap, &soap_tmp_ns__test1, "ns:test1", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__test1(soap, soap_tmp_ns__test1.input, soap_tmp_ns__test1Response.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = ""; /* use SOAP encoding style */
	soap_serializeheader(soap);
	soap_serialize_ns__test1Response(soap, &soap_tmp_ns__test1Response);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__test1Response(soap, &soap_tmp_ns__test1Response, "ns:test1Response", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__test1Response(soap, &soap_tmp_ns__test1Response, "ns:test1Response", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.cpp */
