/* soapStub.h
   Generated by gSOAP 2.8.101 for iMesImage.h

gSOAP XML Web services tools
Copyright (C) 2000-2020, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/


#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 208101
# error "GSOAP VERSION 208101 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes, Structs and Unions                                                *
 *                                                                            *
\******************************************************************************/

struct ns__uploadDataResponse;	/* iMesImage.h:7 */
struct ns__uploadData;	/* iMesImage.h:7 */
struct ns__DownloadDataResponse;	/* iMesImage.h:8 */
struct ns__DownloadData;	/* iMesImage.h:8 */
struct ns__test1Response;	/* iMesImage.h:9 */
struct ns__test1;	/* iMesImage.h:9 */

/* iMesImage.h:7 */
#ifndef SOAP_TYPE_ns__uploadDataResponse
#define SOAP_TYPE_ns__uploadDataResponse (9)
/* complex XML schema type 'ns:uploadDataResponse': */
struct SOAP_CMAC ns__uploadDataResponse {
      public:
        /** Optional element 'result' of XML schema type 'xsd:string' */
        char **result;
      public:
        /** Return unique type id SOAP_TYPE_ns__uploadDataResponse */
        long soap_type() const { return SOAP_TYPE_ns__uploadDataResponse; }
        /** Constructor with member initializations */
        ns__uploadDataResponse() : result() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns__uploadDataResponse * SOAP_FMAC2 soap_instantiate_ns__uploadDataResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* iMesImage.h:7 */
#ifndef SOAP_TYPE_ns__uploadData
#define SOAP_TYPE_ns__uploadData (10)
/* complex XML schema type 'ns:uploadData': */
struct SOAP_CMAC ns__uploadData {
      public:
        /** Optional element 'macCode' of XML schema type 'xsd:string' */
        char *macCode;
        /** Optional element 'wipEntityId' of XML schema type 'xsd:string' */
        char *wipEntityId;
      public:
        /** Return unique type id SOAP_TYPE_ns__uploadData */
        long soap_type() const { return SOAP_TYPE_ns__uploadData; }
        /** Constructor with member initializations */
        ns__uploadData() : macCode(), wipEntityId() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns__uploadData * SOAP_FMAC2 soap_instantiate_ns__uploadData(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* iMesImage.h:8 */
#ifndef SOAP_TYPE_ns__DownloadDataResponse
#define SOAP_TYPE_ns__DownloadDataResponse (12)
/* complex XML schema type 'ns:DownloadDataResponse': */
struct SOAP_CMAC ns__DownloadDataResponse {
      public:
        /** Optional element 'value' of XML schema type 'xsd:string' */
        char **value;
      public:
        /** Return unique type id SOAP_TYPE_ns__DownloadDataResponse */
        long soap_type() const { return SOAP_TYPE_ns__DownloadDataResponse; }
        /** Constructor with member initializations */
        ns__DownloadDataResponse() : value() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns__DownloadDataResponse * SOAP_FMAC2 soap_instantiate_ns__DownloadDataResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* iMesImage.h:8 */
#ifndef SOAP_TYPE_ns__DownloadData
#define SOAP_TYPE_ns__DownloadData (13)
/* complex XML schema type 'ns:DownloadData': */
struct SOAP_CMAC ns__DownloadData {
      public:
        /** Optional element 'data' of XML schema type 'xsd:string' */
        char *data;
      public:
        /** Return unique type id SOAP_TYPE_ns__DownloadData */
        long soap_type() const { return SOAP_TYPE_ns__DownloadData; }
        /** Constructor with member initializations */
        ns__DownloadData() : data() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns__DownloadData * SOAP_FMAC2 soap_instantiate_ns__DownloadData(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* iMesImage.h:9 */
#ifndef SOAP_TYPE_ns__test1Response
#define SOAP_TYPE_ns__test1Response (17)
/* complex XML schema type 'ns:test1Response': */
struct SOAP_CMAC ns__test1Response {
      public:
        /** Required element 'result' of XML schema type 'xsd:string' */
        std::string result;
      public:
        /** Return unique type id SOAP_TYPE_ns__test1Response */
        long soap_type() const { return SOAP_TYPE_ns__test1Response; }
        /** Constructor with member initializations */
        ns__test1Response() : result() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns__test1Response * SOAP_FMAC2 soap_instantiate_ns__test1Response(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* iMesImage.h:9 */
#ifndef SOAP_TYPE_ns__test1
#define SOAP_TYPE_ns__test1 (18)
/* complex XML schema type 'ns:test1': */
struct SOAP_CMAC ns__test1 {
      public:
        /** Required element 'input' of XML schema type 'xsd:string' */
        std::string input;
      public:
        /** Return unique type id SOAP_TYPE_ns__test1 */
        long soap_type() const { return SOAP_TYPE_ns__test1; }
        /** Constructor with member initializations */
        ns__test1() : input() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns__test1 * SOAP_FMAC2 soap_instantiate_ns__test1(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* iMesImage.h:12 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (19)
/* SOAP_ENV__Header: */
struct SOAP_CMAC SOAP_ENV__Header {
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Header */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Header; }
        /** Constructor with member initializations */
        SOAP_ENV__Header() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* iMesImage.h:12 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (20)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_CMAC SOAP_ENV__Code {
      public:
        /** Optional element 'SOAP-ENV:Value' of XML schema type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Code */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Code; }
        /** Constructor with member initializations */
        SOAP_ENV__Code() : SOAP_ENV__Value(), SOAP_ENV__Subcode() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* iMesImage.h:12 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (22)
/* SOAP_ENV__Detail: */
struct SOAP_CMAC SOAP_ENV__Detail {
      public:
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_<typename> assigned to __type */
        /** Do not create a cyclic data structure through this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Detail */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Detail; }
        /** Constructor with member initializations */
        SOAP_ENV__Detail() : __any(), __type(), fault() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* iMesImage.h:12 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (25)
/* SOAP_ENV__Reason: */
struct SOAP_CMAC SOAP_ENV__Reason {
      public:
        /** Optional element 'SOAP-ENV:Text' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Text;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Reason */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Reason; }
        /** Constructor with member initializations */
        SOAP_ENV__Reason() : SOAP_ENV__Text() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* iMesImage.h:12 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (26)
/* SOAP_ENV__Fault: */
struct SOAP_CMAC SOAP_ENV__Fault {
      public:
        /** Optional element 'faultcode' of XML schema type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XML schema type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XML schema type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XML schema type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Fault */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Fault; }
        /** Constructor with member initializations */
        SOAP_ENV__Fault() : faultcode(), faultstring(), faultactor(), detail(), SOAP_ENV__Code(), SOAP_ENV__Reason(), SOAP_ENV__Node(), SOAP_ENV__Role(), SOAP_ENV__Detail() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* (built-in):0 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
typedef char *_XML;
#endif

/* (built-in):0 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
typedef char *_QName;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* std::string has binding name 'std__string' for type 'xsd:string' */
#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (14)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (26)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (25)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (22)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (20)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (19)
#endif

/* struct ns__test1 has binding name 'ns__test1' for type 'ns:test1' */
#ifndef SOAP_TYPE_ns__test1
#define SOAP_TYPE_ns__test1 (18)
#endif

/* struct ns__test1Response has binding name 'ns__test1Response' for type 'ns:test1Response' */
#ifndef SOAP_TYPE_ns__test1Response
#define SOAP_TYPE_ns__test1Response (17)
#endif

/* struct ns__DownloadData has binding name 'ns__DownloadData' for type 'ns:DownloadData' */
#ifndef SOAP_TYPE_ns__DownloadData
#define SOAP_TYPE_ns__DownloadData (13)
#endif

/* struct ns__DownloadDataResponse has binding name 'ns__DownloadDataResponse' for type 'ns:DownloadDataResponse' */
#ifndef SOAP_TYPE_ns__DownloadDataResponse
#define SOAP_TYPE_ns__DownloadDataResponse (12)
#endif

/* struct ns__uploadData has binding name 'ns__uploadData' for type 'ns:uploadData' */
#ifndef SOAP_TYPE_ns__uploadData
#define SOAP_TYPE_ns__uploadData (10)
#endif

/* struct ns__uploadDataResponse has binding name 'ns__uploadDataResponse' for type 'ns:uploadDataResponse' */
#ifndef SOAP_TYPE_ns__uploadDataResponse
#define SOAP_TYPE_ns__uploadDataResponse (9)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (28)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (27)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (21)
#endif

/* char ** has binding name 'PointerTostring' for type 'xsd:string' */
#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (7)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stub Functions                                            *
 *                                                                            *
\******************************************************************************/

    
    /** Web service synchronous operation 'soap_call_ns__uploadData' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__uploadData(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *macCode, char *wipEntityId, char **result);
    /** Web service asynchronous operation 'soap_send_ns__uploadData' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns__uploadData(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *macCode, char *wipEntityId);
    /** Web service asynchronous operation 'soap_recv_ns__uploadData' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns__uploadData(struct soap *soap, char **result);
    
    /** Web service synchronous operation 'soap_call_ns__DownloadData' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__DownloadData(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *data, char **value);
    /** Web service asynchronous operation 'soap_send_ns__DownloadData' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns__DownloadData(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *data);
    /** Web service asynchronous operation 'soap_recv_ns__DownloadData' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns__DownloadData(struct soap *soap, char **value);
    
    /** Web service synchronous operation 'soap_call_ns__test1' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__test1(struct soap *soap, const char *soap_endpoint, const char *soap_action, const std::string& input, std::string &result);
    /** Web service asynchronous operation 'soap_send_ns__test1' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns__test1(struct soap *soap, const char *soap_endpoint, const char *soap_action, const std::string& input);
    /** Web service asynchronous operation 'soap_recv_ns__test1' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns__test1(struct soap *soap, std::string &result);

/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/

    /** Web service operation 'ns__uploadData' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 ns__uploadData(struct soap*, char *macCode, char *wipEntityId, char **result);
    /** Web service operation 'ns__DownloadData' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 ns__DownloadData(struct soap*, char *data, char **value);
    /** Web service operation 'ns__test1' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 ns__test1(struct soap*, std::string input, std::string &result);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__uploadData(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__DownloadData(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__test1(struct soap*);

#endif

/* End of soapStub.h */
